
bridges = []

[[instances]]
name = "cc_tuts"
id = "__cc_tuts"
dna_hash = "QmXayr6HwonU8tm7UrkKjQf13zL5g6ifRs1F4Qr1vNXuzj"
uri = "file:dist/cc_tuts.dna.json"

[[UIs]]
name = "CC Tuts"
id = "cc_tuts_ui"
uri = "dir:../gui"

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__cc_tuts"