
bridges = []

[[instances]]
name = "cc_tuts"
id = "__cc_tuts"
dna_hash = "QmVCcHk6UnPV4ot3nUoXgKMyefk3fLWvJFik2PZmE9JCgT"
uri = "file:dist/cc_tuts.dna.json"

[[UIs]]
name = "CC Tuts"
id = "cc_tuts_ui"
uri = "dir:../gui"

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "__cc_tuts"